export const TYPES = {
    ROOT: 'ROOT', 
    GRASS: 'GRASS',
    
    FLOWER_GARDEN: 'FLOWER_GARDEN',
    FLOWER_GARDEN_RED: 'FLOWER_GARDEN_RED',
    FLOWER_GARDEN_ORANGE: 'FLOWER_GARDEN_ORANGE',
    FLOWER_GARDEN_PINK: 'FLOWER_GARDEN_PINK',
    FLOWER_GARDEN_PURPLE: 'FLOWER_GARDEN_PURPLE',
    FLOWER_GARDEN_BLUE: 'FLOWER_GARDEN_BLUE',

    FOREST: 'FOREST',
    FOREST_T1: 'FOREST_T1',
    FOREST_T2: 'FOREST_T2',
    FOREST_T3: 'FOREST_T3',
    FOREST_T4: 'FOREST_T4',

    POND: 'POND',
    FLOWER_POND_T1: 'FLOWER_POND_T1',
    FLOWER_POND_T2: 'FLOWER_POND_T2',

    FOUNTAIN: 'FOUNTAIN', 
    FOUNTAINT_BENCH_T1: 'FOUNTAINT_BENCH_T1'
};

export const COLORS = {
    ROOT: '#ffffff', 
    GRASS: '#8bc34a', 
    PATH: '#cfd8dc', 
    
    FLOWER_GARDEN: '#e91e63', 
    FLOWER_GARDEN_RED: '#e53935', 
    FLOWER_GARDEN_ORANGE: '#fb8c00',
    FLOWER_GARDEN_PINK: '#f06292',
    FLOWER_GARDEN_PURPLE: '#8e24aa',
    FLOWER_GARDEN_BLUE: '#1e88e5',

    FOREST: '#2e7d32',
    FOREST_T1: '#1b5e20',
    FOREST_T2: '#43a047',
    FOREST_T3: '#004d40',
    FOREST_T4: '#558b2f',

    POND: '#4fc3f7',         
    FLOWER_POND_T1: '#81d4fa', 
    FLOWER_POND_T2: '#0288d1', 

    FOUNTAIN: '#03a9f4', 
    BENCH: '#795548',
    FOUNTAINT_BENCH_T1: '#b0bec5'
};